### ISSUE TITLE
How long will the MatterportEchoes dataset be released?

### ISSUE THREAD

**Issue by qqsh0214** [krantiparida/beyond-image-to-depth#7]
Hello, thanks for your excellent and hard work ! Could you please tell the approximate time for the MatterportEchoes dataset to be released? I really want to follow your work. Thanks !

**Comment by krantiparida** [comment]
Hi, you can find the echoes for Matterport dataset in this [link](https://drive.google.com/drive/folders/1wgioF6FROoK9VLh6gLdvKfUzUrSGG7e8?usp=sharing). We cannot share the extracted frames directly due to the restriction from Matterport. However, you can use the steps mentioned in the [SoundSpaces](https://github.com/facebookresearch/sound-spaces/tree/main/soundspaces) repo to generate those frames.
